# Hyprgrass plugin and touchscreen gestures (Surface only)
plugin = /etc/hypr/plugins/hyprgrass.so

plugin {
    touch_gestures {
        sensitivity = 4.0
        workspace_swipe = true
        workspace_swipe_fingers = 3
        workspace_swipe_edge = r
        workspace_swipe_cancel_ratio = 0.15
        emulate_touchpad_swipe = true
        long_press_delay = 400
        edge_margin = 100
        hyprgrass-bind = , swipe:2:l, movewindow, l
        hyprgrass-bind = , swipe:2:r, movewindow, r
        hyprgrass-bind = , swipe:2:u, movewindow, u
        hyprgrass-bind = , swipe:2:d, movewindow, d
        hyprgrass-bind = , edge:u:d, exec, wtype -M logo -m logo
        hyprgrass-bind = , edge:d:u, exec, wvkbd-mobintl -H 400 -L 300
        hyprgrass-bind = , edge:d:d, exec, pkill wvkbd
        hyprgrass-bind = , edge:3:u:d, killactive
        hyprgrass-bind = , edge:r:l, workspace, +1
        hyprgrass-bind = , edge:l:r, workspace, -1
        hyprgrass-bind = , tap:3, exec, wvkbd-mobintl -H 400 -L 300
        hyprgrass-bind = , tap:4, exec, pkill wvkbd
        hyprgrass-bind = , edge:l:d, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 4%-
        hyprgrass-bind = , edge:l:u, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 4%+
        hyprgrass-bindm = , longpress:2, movewindow
        hyprgrass-bindm = , longpress:3, resizewindow
        hyprgrass-bind = , pinch:4:o, fullscreen, 1
        hyprgrass-bind = , pinch:4:i, fullscreen, 0
    }
}
