alias ta='tmux attach-session -d -t'
alias tl='tmux list-sessions'
alias tc='tmux'
alias ls='eza'
alias vim="nvim"
alias vimdiff="nvim -d"
alias make="ponymake"
alias yarn="ponyyarn"
alias fly="ponyfly"
alias pnpm="ponypnpm"
alias cargo="ponycargo"
alias podman="ponypodman"
alias bloop="ponybloop"
alias cmake="ponycmake"
alias invoke="ponyinvoke"
alias lg="lazygit"
alias cat="bat"
alias gd="git diff"
alias gs="git status"
alias gm="git mergetool"
